Update `ss-obfs`.
# - Upgrade shadowsocks-libev to v3.1.0 & simple-obfs to v0.0.5.
# - Add a build argument for enabling traffic obfuscation or not.

diff --git a/ss-obfs/Dockerfile b/ss-obfs/Dockerfile
--- a/ss-obfs/Dockerfile
+++ b/ss-obfs/Dockerfile
@@ -1,88 +1,103 @@
-FROM quchao/base
-LABEL maintainer "Chao QU <mail@quchao.com>"
+FROM nutshells/base
+LABEL maintainer 'Chao QU <mail@quchao.com>'
 
-WORKDIR /etc/shadowsocks-libev/
+ARG SS_VERSION='3.1.0'
+ARG SS_SHA256='3b6493ebdcfff1eb31faf34d164d57049f7253ff5bffafa6ce2263c9ac123f31'
+ARG OBFS_VERSION='0.0.5'
+ARG OBFS_SHA256='0de9b551b67ec82d0af9d09bcb74c9e8d047f0082ae07db8e4f5f3defeb2ce4c'
+ARG LIBCORK_COMMIT='29d7cba'
+ARG LIBCORK_SHA256='52be7bddaf4cbcf8635c616b69c1b89e776ad2b19458a3e8c80fc1c30b13f79d'
+ENV WITH_OBFS='true'
 
-ARG SS_VERSION="3.0.6"
-ARG SS_SHA256="7d9b43b0235a57c115bfe160efd54abef96bffcbfff61c5496e7c2800f0734ca"
-ARG OBFS_VERSION="0.0.3"
-ARG OBFS_SHA256="350c22e138202868d5726cb55e3d71e9962aad3306988a9f746b80d0e8998a75"
-ARG LIBCORK_COMMIT="3bcb832"
-ARG LIBCORK_SHA256="c229dbfe754ec376f906043a35b1fb10725226c6c7136911cf817c92fc170959"
+WORKDIR /usr/local/src/
 
 RUN set -ex; \
-    mkdir -p /usr/local/src/; \
-    cd /usr/local/src/; \
     # build deps
     apk add --no-cache --virtual .build-deps \
         build-base \
+        linux-headers \
         autoconf \
         automake \
         libtool \
-        linux-headers \
-    ; \
-    # runtime deps
-    apk add --no-cache --virtual .runtime-deps \
         mbedtls-dev \
         libev-dev \
         libsodium-dev \
-        udns-dev \
+        c-ares-dev \
         pcre-dev \
     ; \
+    # runtime deps
+    apk add --no-cache --virtual .runtime-deps \
+        mbedtls \
+        libev \
+        libsodium \
+        c-ares \
+        pcre \
+    ; \
     # ss-libev
-    curl -LO https://github.com/shadowsocks/shadowsocks-libev/releases/download/v${SS_VERSION}/shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    echo "${SS_SHA256}  shadowsocks-libev-${SS_VERSION}.tar.gz" | sha256sum -c; \
-    tar xzf shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    cd shadowsocks-libev-${SS_VERSION}; \
+    curl -sSLO "https://github.com/shadowsocks/shadowsocks-libev/releases/download/v${SS_VERSION}/shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    echo "${SS_SHA256}  shadowsocks-libev-${SS_VERSION}.tar.gz" | sha256sum -c -; \
+    tar xzf "shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    cd "shadowsocks-libev-${SS_VERSION}"; \
     ./configure --disable-documentation; \
     make; \
     #make check; \
-    make install; \
+    #make install; \
+    cp src/ss-server src/ss-local /usr/local/bin/; \
     #make installcheck; \
     cd ..; \
-    rm -f shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    rm -rf shadowsocks-libev-${SS_VERSION}; \
-    # simple-obfs
-    curl -LO https://github.com/shadowsocks/simple-obfs/archive/v${OBFS_VERSION}.tar.gz; \
-    echo "${OBFS_SHA256}  v${OBFS_VERSION}.tar.gz" | sha256sum -c -; \
-    tar xzf v${OBFS_VERSION}.tar.gz; \
-    cd simple-obfs-${OBFS_VERSION}; \
-    # libcork
-    rm -rf libcork; \
-    curl -LO https://github.com/shadowsocks/libcork/archive/${LIBCORK_COMMIT}.tar.gz; \
-    echo "${LIBCORK_SHA256}  ${LIBCORK_COMMIT}.tar.gz" | sha256sum -c -; \
-    tar xzf ${LIBCORK_COMMIT}.tar.gz; \
-    mv libcork-* libcork; \
-    ./autogen.sh; \
-    ./configure --disable-documentation; \
-    make; \
-    #make check; \
-    make install; \
-    #make installcheck; \
-    cd ..; \
-    rm -f simple-obfs-${OBFS_VERSION}.tar.gz; \
-    rm -rf simple-obfs-${OBFS_VERSION}; \
-    # cleaning
-    apk del .build-deps; \
+    rm -f "shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    rm -rf "shadowsocks-libev-${SS_VERSION}"; \
+    if [ "${WITH_OBFS}" = 'true' ]; then \
+        # simple-obfs
+        curl -sSLO "https://github.com/shadowsocks/simple-obfs/archive/v${OBFS_VERSION}.tar.gz"; \
+        echo "${OBFS_SHA256}  v${OBFS_VERSION}.tar.gz" | sha256sum -c -; \
+        tar xzf "v${OBFS_VERSION}.tar.gz"; \
+        cd "simple-obfs-${OBFS_VERSION}"; \
+        # libcork
+        rm -rf libcork; \
+        curl -sSLO "https://github.com/shadowsocks/libcork/archive/${LIBCORK_COMMIT}.tar.gz"; \
+        echo "${LIBCORK_SHA256}  ${LIBCORK_COMMIT}.tar.gz" | sha256sum -c -; \
+        tar xzf "${LIBCORK_COMMIT}.tar.gz"; \
+        mv libcork-* libcork; \
+        ./autogen.sh; \
+        ./configure --disable-documentation; \
+        make; \
+        #make check; \
+        #make install; \
+        cp src/obfs-server src/obfs-local /usr/local/bin/; \
+        #make installcheck; \
+        cd ..; \
+        rm -f "simple-obfs-${OBFS_VERSION}.tar.gz"; \
+        rm -rf "simple-obfs-${OBFS_VERSION}"; \
+    fi; \
+    # do some cleanup
+    apk del --purge .build-deps; \
     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/local/src/*;
 
-# Set password in server.json
-# Set password, server ip and port in client.json
-COPY server.json client.json /etc/shadowsocks-libev/
 COPY docker-entrypoint.sh /usr/local/bin/
 
 RUN set -ex; \
     chmod +x /usr/local/bin/docker-entrypoint.sh; \
-    # User/Group
-    addgroup -S shadowsocks; \
-    adduser -S -D -H -h /var/empty -s /sbin/nologin -G shadowsocks shadowsocks;
+    chown "${RUN_AS_USER}":"${RUN_AS_USER}" /usr/local/bin/ss-*; \
+    chown "${RUN_AS_USER}":"${RUN_AS_USER}" /usr/local/bin/obfs-*;
 
-ENV APP_PORT="12345"
+ENV LISTEN_PORT='12345' \
+    SERVER_ADDRESS='' \
+    SERVER_PORT='' \
+    PASSWORD='' \
+    KEY_IN_BASE64='' \
+    ENCRYPT_METHOD='xchacha20-ietf-poly1305' \
+    TCP_RELAY='true' \
+    UDP_RELAY='true' \
+    REUSE_PORT='true' \
+    TCP_FAST_OPEN='true' \
+    OBFS_PLUGIN='http' \
+    OBFS_HOST='bing.com'
 
-HEALTHCHECK --interval=1m --timeout=3s \
-    CMD [ 1 == $(curl -f http://localhost:${APP_PORT} 2>&1 | grep 'curl: (52)' | wc -l) ] || exit 1
+#HEALTHCHECK --interval=1m --timeout=3s \
+#    CMD [[ "$(curl -f http://localhost:"${LISTEN_PORT}" 2>&1 | grep 'curl: (52)' | wc -l)" -eq 1 ]] || exit 1
 
+EXPOSE ${LISTEN_PORT}/tcp ${LISTEN_PORT}/udp
+
+WORKDIR /usr/local/var/ss-obfs
 ENTRYPOINT [ "docker-entrypoint.sh" ]
-CMD [ "ss-server" ]
-
-EXPOSE ${APP_PORT}/tcp ${APP_PORT}/udp
diff --git a/ss-obfs/Dockerfile-centos b/ss-obfs/Dockerfile-centos
--- a/ss-obfs/Dockerfile-centos
+++ b/ss-obfs/Dockerfile-centos
@@ -1,24 +1,24 @@
-FROM quchao/base:centos
+FROM nutshells/base:centos
 LABEL maintainer "Chao QU <mail@quchao.com>"
 
-WORKDIR /etc/shadowsocks-libev/
-
-ARG SS_VERSION="3.0.6"
-ARG SS_SHA256="7d9b43b0235a57c115bfe160efd54abef96bffcbfff61c5496e7c2800f0734ca"
-ARG OBFS_VERSION="0.0.3"
-ARG OBFS_SHA256="350c22e138202868d5726cb55e3d71e9962aad3306988a9f746b80d0e8998a75"
+ARG SS_VERSION="3.1.0"
+ARG SS_SHA256="3b6493ebdcfff1eb31faf34d164d57049f7253ff5bffafa6ce2263c9ac123f31"
+ARG OBFS_VERSION='0.0.5'
+ARG OBFS_SHA256='0de9b551b67ec82d0af9d09bcb74c9e8d047f0082ae07db8e4f5f3defeb2ce4c'
 ARG LIBSODIUM_VERSION="1.0.12"
 ARG LIBSODIUM_SHA256="b8648f1bb3a54b0251cf4ffa4f0d76ded13977d4fa7517d988f4c902dd8e2f95"
 ARG LIBMBEDTLS_VERSION="2.4.2"
 ARG LIBMBEDTLS_SHA256="b7afab6a0f86e29c6055848b70d183c4e2531cb0ec955b66c0e4e1b7e4954bf4"
 ARG LIBUDNS_VERSION="0.4"
 ARG LIBUDNS_SHA256="115108dc791a2f9e99e150012bcb459d9095da2dd7d80699b584ac0ac3768710"
-ARG LIBCORK_COMMIT="3bcb832"
-ARG LIBCORK_SHA256="c229dbfe754ec376f906043a35b1fb10725226c6c7136911cf817c92fc170959"
+ARG LIBCORK_COMMIT='29d7cba'
+ARG LIBCORK_SHA256='52be7bddaf4cbcf8635c616b69c1b89e776ad2b19458a3e8c80fc1c30b13f79d'
+ENV WITH_OBFS='true'
+
+WORKDIR /usr/local/src/
 
 # Dev Tools & Deps
 RUN set -ex; \
-    cd /usr/local/src/; \
     # build & runtime deps
     yum install -y \
         gcc \
@@ -27,82 +27,72 @@ RUN set -ex; \
         libtool \
         make \
         pcre-devel \
+        c-ares-devel \
         libev-devel; \
     # libsodium (v1.0.8+) \
-    curl -LO https://github.com/jedisct1/libsodium/releases/download/${LIBSODIUM_VERSION}/libsodium-${LIBSODIUM_VERSION}.tar.gz; \
-    echo "${LIBSODIUM_SHA256}  libsodium-${LIBSODIUM_VERSION}.tar.gz" | sha256sum -c; \
-    tar xvf libsodium-${LIBSODIUM_VERSION}.tar.gz; \
-    pushd libsodium-${LIBSODIUM_VERSION}; \
-    ./configure --prefix=/usr; \
-    make; \
+    curl -sSLO "https://github.com/jedisct1/libsodium/releases/download/${LIBSODIUM_VERSION}/libsodium-${LIBSODIUM_VERSION}.tar.gz"; \
+    echo "${LIBSODIUM_SHA256}  libsodium-${LIBSODIUM_VERSION}.tar.gz" | sha256sum -c -; \
+    tar xvf "libsodium-${LIBSODIUM_VERSION}.tar.gz"; \
+    pushd "libsodium-${LIBSODIUM_VERSION}"; \
+    env CFLAGS=-Ofast ./configure --disable-dependency-tracking --prefix=/usr; \
+    #make; \
     #make check; \
     make install; \
     #make installcheck; \
     popd; \
-    ldconfig; \
-    rm -f libsodium-${LIBSODIUM_VERSION}.tar.gz; \
-    rm -rf libsodium-${LIBSODIUM_VERSION}; \
+    #ldconfig; \
+    rm -f "libsodium-${LIBSODIUM_VERSION}.tar.gz"; \
+    rm -rf "libsodium-${LIBSODIUM_VERSION}"; \
     # libmbedtls
-    curl -LO https://github.com/ARMmbed/mbedtls/archive/mbedtls-${LIBMBEDTLS_VERSION}.tar.gz; \
-    echo "${LIBMBEDTLS_SHA256}  mbedtls-${LIBMBEDTLS_VERSION}.tar.gz" | sha256sum -c; \
-    tar xvf mbedtls-${LIBMBEDTLS_VERSION}.tar.gz; \
-    pushd mbedtls-mbedtls-${LIBMBEDTLS_VERSION}; \
+    curl -sSLO "https://github.com/ARMmbed/mbedtls/archive/mbedtls-${LIBMBEDTLS_VERSION}.tar.gz"; \
+    echo "${LIBMBEDTLS_SHA256}  mbedtls-${LIBMBEDTLS_VERSION}.tar.gz" | sha256sum -c -; \
+    tar xvf "mbedtls-${LIBMBEDTLS_VERSION}.tar.gz"; \
+    pushd "mbedtls-mbedtls-${LIBMBEDTLS_VERSION}"; \
     make SHARED=1 CFLAGS=-fPIC; \
     make DESTDIR=/usr install; \
     popd; \
-    ldconfig; \
-    rm -f mbedtls-${LIBMBEDTLS_VERSION}.tar.gz; \
-    rm -rf mbedtls-mbedtls-${LIBMBEDTLS_VERSION}; \
-    # libudns
-    curl -LO http://www.corpit.ru/mjt/udns/udns-${LIBUDNS_VERSION}.tar.gz; \
-    echo "${LIBUDNS_SHA256}  udns-${LIBUDNS_VERSION}.tar.gz" | sha256sum -c; \
-    tar xvf udns-${LIBUDNS_VERSION}.tar.gz; \
-    pushd udns-${LIBUDNS_VERSION}; \
-    ./configure; \
-    make shared; \
-    cp udns.h /usr/include/; \
-    cp libudns.so.0 /usr/lib/; \
-    cd /usr/lib/; \
-    ln -s libudns.so.0 libudns.so; \
-    popd; \
-    ldconfig; \
-    rm -f udns-${LIBUDNS_VERSION}.tar.gz; \
-    rm -rf udns-${LIBUDNS_VERSION}; \
+    #ldconfig; \
+    rm -f "mbedtls-${LIBMBEDTLS_VERSION}.tar.gz"; \
+    rm -rf "mbedtls-mbedtls-${LIBMBEDTLS_VERSION}"; \
     # shadowsocks-libev
-    curl -LO https://github.com/shadowsocks/shadowsocks-libev/releases/download/v${SS_VERSION}/shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    echo "${SS_SHA256}  shadowsocks-libev-${SS_VERSION}.tar.gz" | sha256sum -c; \
-    tar xvf shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    pushd shadowsocks-libev-${SS_VERSION}; \
+    curl -sSLO "https://github.com/shadowsocks/shadowsocks-libev/releases/download/v${SS_VERSION}/shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    echo "${SS_SHA256}  shadowsocks-libev-${SS_VERSION}.tar.gz" | sha256sum -c -; \
+    tar xvf "shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    pushd "shadowsocks-libev-${SS_VERSION}"; \
     #autoreconf --install --force; \
     ./configure --disable-documentation; \
     make; \
     #make check; \
-    make install; \
+    #make install; \
+    cp src/ss-server src/ss-local /usr/local/bin/; \
     #make installcheck; \
     popd; \
-    rm -f shadowsocks-libev-${SS_VERSION}.tar.gz; \
-    rm -rf shadowsocks-libev-${SS_VERSION}; \
-    # simple-obfs
-    curl -LO https://github.com/shadowsocks/simple-obfs/archive/v${OBFS_VERSION}.tar.gz; \
-    echo "${OBFS_SHA256}  v${OBFS_VERSION}.tar.gz" | sha256sum -c; \
-    tar xvf v${OBFS_VERSION}.tar.gz; \
-    pushd simple-obfs-${OBFS_VERSION}; \
-    # libcork
-    curl -LO https://github.com/shadowsocks/libcork/archive/${LIBCORK_COMMIT}.tar.gz; \
-    echo "${LIBCORK_SHA256}  ${LIBCORK_COMMIT}.tar.gz" | sha256sum -c; \
-    tar xvf ${LIBCORK_COMMIT}.tar.gz; \
-    rm -rf libcork; \
-    mv libcork-* libcork; \
-    ./autogen.sh; \
-    ./configure --disable-documentation; \
-    make; \
-    #make check; \
-    make install; \
-    #make installcheck; \
-    popd; \
-    rm -f v${OBFS_VERSION}.tar.gz; \
-    rm -rf simple-obfs-${OBFS_VERSION}; \
-    # Cleaning
+    rm -f "shadowsocks-libev-${SS_VERSION}.tar.gz"; \
+    rm -rf "shadowsocks-libev-${SS_VERSION}"; \
+    if [ "${WITH_OBFS}" = 'true' ]; then \
+        # simple-obfs
+        curl -sSLO "https://github.com/shadowsocks/simple-obfs/archive/v${OBFS_VERSION}.tar.gz"; \
+        echo "${OBFS_SHA256}  v${OBFS_VERSION}.tar.gz" | sha256sum -c; \
+        tar xvf "v${OBFS_VERSION}.tar.gz"; \
+        pushd "simple-obfs-${OBFS_VERSION}"; \
+        # libcork
+        curl -sSLO "https://github.com/shadowsocks/libcork/archive/${LIBCORK_COMMIT}.tar.gz"; \
+        echo "${LIBCORK_SHA256}  ${LIBCORK_COMMIT}.tar.gz" | sha256sum -c; \
+        tar xvf "${LIBCORK_COMMIT}.tar.gz"; \
+        rm -rf libcork; \
+        mv libcork-* libcork; \
+        ./autogen.sh; \
+        ./configure --disable-documentation; \
+        make; \
+        #make check; \
+        #make install; \
+        cp src/obfs-server src/obfs-local /usr/local/bin/; \
+        #make installcheck; \
+        popd; \
+        rm -f "v${OBFS_VERSION}.tar.gz"; \
+        rm -rf "simple-obfs-${OBFS_VERSION}"; \
+    fi; \
+    # do some cleanup
     yum remove -y \
         gcc \
         autoconf \
@@ -112,25 +102,32 @@ RUN set -ex; \
 	yum clean all; \
     rm -rf /tmp/* /var/tmp/* /usr/local/src/*;
 
-# Set password in server.json
-# Set password, server ip and port in client.json
-COPY server.json client.json /etc/shadowsocks-libev/
 COPY docker-entrypoint.sh /usr/local/bin/
 
 RUN set -ex; \
     # Use GoSU instead
     sed -i 's/su-exec/gosu/' /usr/local/bin/docker-entrypoint.sh; \
     chmod +x /usr/local/bin/docker-entrypoint.sh; \
-    # User/Group
-    groupadd -r shadowsocks; \
-    useradd -M -d /var/empty -s /sbin/nologin -g shadowsocks -r shadowsocks;
+    chown "${RUN_AS_USER}":"${RUN_AS_USER}" /usr/local/bin/ss-*; \
+    chown "${RUN_AS_USER}":"${RUN_AS_USER}" /usr/local/bin/obfs-*;
 
-ENV APP_PORT="12345"
+ENV LISTEN_PORT='12345' \
+    SERVER_ADDRESS='' \
+    SERVER_PORT='' \
+    PASSWORD='' \
+    KEY_IN_BASE64='' \
+    ENCRYPT_METHOD='xchacha20-ietf-poly1305' \
+    TCP_RELAY='true' \
+    UDP_RELAY='true' \
+    REUSE_PORT='true' \
+    TCP_FAST_OPEN='true' \
+    OBFS_PLUGIN='http' \
+    OBFS_HOST='bing.com'
 
-HEALTHCHECK --interval=1m --timeout=3s \
-    CMD [ 1 == $(curl -f http://localhost:${APP_PORT} 2>&1 | grep 'curl: (52)' | wc -l) ] || exit 1
+#HEALTHCHECK --interval=1m --timeout=3s \
+#    CMD [[ "$(curl -f http://localhost:"${LISTEN_PORT}" 2>&1 | grep 'curl: (52)' | wc -l)" -eq 1 ]] || exit 1
 
+EXPOSE ${LISTEN_PORT}/tcp ${LISTEN_PORT}/udp
+
+WORKDIR /usr/local/var/ss-obfs
 ENTRYPOINT [ "docker-entrypoint.sh" ]
-CMD [ "ss-server" ]
-
-EXPOSE ${APP_PORT}/tcp ${APP_PORT}/udp
